### PR TITLE
Added Slim and Twig

### PR DESCRIPTION
**Pull request by MisterBrownRSA**
All the Jetbrains Licenses are belong to us.

### CODE REVIEW

**Comment by mostertb** [comment]
This is looking very cool!

Looks like you currently have a syntax error in the composer.json (see the Travis CI build on this page for details)

Also would it be possible to use the `mostertb\PHPSA2017Profiles` namespace for the code you've added under `App` rather than creating some new `App` namespace which might conflict with other packages?

**Comment by MisterBrownRSA** [comment]
Sure. No Problem.

**Comment by mostertb** [comment]
@MisterBrownRSA This is finally merged. It looks awesome! Thank you so much

**Comment by mostertb** [comment]
Are you on twitter? I'd very much like to tweet about you PR...

**Comment by MisterBrownRSA** [comment]
Hey man.

I opened a new issue to try and solve the issue the site is currently experiencing.

As for the twitter thing, I personally don't use Twitter, so please use my company's handle: @HashtecZA

**Pull request merged**
